### ISSUE TITLE
`VertxHttpClientHTTPConduit` does not honor default Java truststore

### ISSUE THREAD

**Issue by jcjveraa** [quarkiverse/quarkus-cxf#1665]
Edit by @ppalaga: 

`VertxHttpClientHTTPConduit` does not honor the default Java trust store, typically `${JAVA_HOME}/lib/security/cacerts` unless the same file is configured explicitly in `application.properties`. This breaks the drop-in compatibility with the old default `URLConnectionHTTPConduit`. 

Original report by @jcjveraa : 

Hi there, upgrading a quarkus microservice with this extension from 3.15 to 3.16 proves to be a bit of a challenge for me. I have read the changelogs etc. but cannot figure how to change my configuration to work again.
 
Issue: I'm sending my requests via a simple basic-auth over single-sided https to another server. With quarkus 3.15.1 this works fine. When trying to migrate to 3.16.4 (= cxf plugin 3.16.1) suddenly the https call seems to be downgraded to plain http, as the target server responds with a SOAP message containing an application-specific security error which occurs when sending http-requests to the https-endpoint. 
 
The standard java `cacerts` include the target server's CA certificates, in other words the host on which my application runs trusts the target server's certification path, so in principle no extra trust store should be required. Nevertheless I've tried setting up a tls config with just a trust store under `quarkus.tls.xxx.trust-store.` (etc.), but then it seems to try to go into mutual TLS mode as then it exits with `Failed to create SSL connection`? Not entirely sure, the error logging is cryptic at best. 
 
Any pointers are very welcome. 
 
My quarkus config (in yaml-mode), working fine for 3.15:
```
cxf:
  client:
    xxx:
      wsdl: classpath:${quarkus.cxf.codegen.wsdl2java.xxx.includes}
      username: ${yyy.zzz.username}
      password: ${yyy.zzz.password}
      secure-wsdl-access: true
      client-endpoint-url: https://the-target.server.com/
  codegen:
    wsdl2java:
      xxx:
        includes: wsdl/xxx/xxx.wsdl
        wsdl-location: classpath:wsdl/xxx/xxx.wsdl
```
