### ISSUE TITLE
Passing of Values from one Interceptor Chain to another Interceptor Chain

### ISSUE THREAD

**Issue by janaarthananselvarjaan** [quarkiverse/quarkus-cxf#648]
`Hi` Team,

I am trying to pass the value from one interceptor(InterceptorOne) to another interceptor(InterceptorTwo) but they belong to different chains. Kindly refer the cxf properties below, i even tried @RequestScoped but it also didn't seem to work. 
```
  cxf:
    client:
      "consume-cxf":
        service-interface: org.sample.ConsumeClient
        client-endpoint-url: http://backend:8080/get/data
        in-interceptors: org.sample.InterceptorTwo
    path: /cxf
    endpoint:
      "/expose":
        implementor: org.sample.ExposeService
        in-interceptors: org.sample.InterceptorOne
```
In this, we are trying to hit the "/cxf/expose" from the postman which will call @CXFClient("consume-cxf") with someMethod() in ConsumeClient class. And in a @requestScoped object we are setting value in InterceptorOne and trying to get the same in InterceptorTwo and that is returning null.
Kindly assist me in this.
